# Generated by Django 3.1.3 on 2020-11-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0003_auto_20201114_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenerurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
