# Generated by Django 3.1.3 on 2020-11-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener_app', '0005_auto_20201114_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('shortener_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener_app.shortenerurl')),
            ],
        ),
    ]
